repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: maven-checkstyle
        name: Maven Checkstyle + Test
        entry: bash -c 'xmllint --noout pom.xml && mvn -q org.apache.maven.plugins:maven-checkstyle-plugin:3.3.1:check -Dcheckstyle.config.location=config/checkstyle.xml -Dcheckstyle.suppressions.file=config/suppressions.xml -Dcheckstyle.includeTestSourceDirectory=true'
        language: system
        types: [java]
        pass_filenames: false
        verbose: true
        stages: [pre-commit]
